
modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/frank89722/BetterSafeBed/issues"
[[mods]] #mandatory
modId="bettersafebed"
version="${file.jarVersion}"
displayName="Better Safe Bed"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-safe-bed"
logoFile="icon.png"
authors="frankV"
description='''
Let you able to sleep when the hostile mobs around the bed can't target you.
'''
[[dependencies.bettersafebed]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"
# Here's another dependency
[[dependencies.bettersafebed]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"