modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/frank89722/BetterSafeBed/issues" #optional
[[mods]] #mandatory
modId="bettersafebed" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Better Safe Bed" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-safe-bed" #optional
logoFile="icon.png" #optional
authors="frankV"
description='''
Let you able to sleep when the hostile mobs around the bed can't target you.
'''
[[dependencies.bettersafebed]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37.0.59,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.bettersafebed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
