modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/frank89722/BetterSafeBed/issues"
[[mods]] #mandatory
modId="bettersafebed"
version="${file.jarVersion}"
displayName="Better Safe Bed"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-safe-bed"
logoFile="icon.png"
authors="frankV"
description='''
Let you able to sleep when the hostile mobs around the bed can't target you.
'''
[[dependencies.bettersafebed]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bettersafebed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[mixins]]
    config="bettersafebed.mixins.json"
